build:
  version: "1.0"

order:
  message: "Welcome to eCommerce Order Category!!!"
  contactDetails:
    name: "Pratap Mishra - Developer"
    email: "pratapmishra23@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345
